[theme]
base="light"
primaryColor="#4A90E2"          # A shade of blue from the logo for primary actions and links
secondaryBackgroundColor="#7BACD2"  # A lighter shade of blue for secondary elements and backgrounds
textColor="#333333"             # A dark grey for text that ensures readability
backgroundColor="#FAFAFA"       # A very light grey for the app's general background, complementing the overall design


[browser]
gatherUsageStats = false

[logger]
# Level of logging: 'error', 'warning', 'info', or 'debug'.
# Default: 'info'
level = "warning"